[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.9", features = ["csr"] }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.9" }
leptos_transition_group = { path = "../../" }
thaw = { git = "https://github.com/tysen/thaw", branch = "leptos_0.9", features = ["csr"] }